# Generated by Django 4.2.1 on 2023-08-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=100, verbose_name='Вкус')),
                ('topping', models.CharField(max_length=100, verbose_name='Топпинг')),
                ('price', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('priority', models.IntegerField(verbose_name='Приоритет')),
                ('due_date', models.DateTimeField(verbose_name='Время выполнения')),
            ],
        ),
    ]
