# Generated by Django 4.2.1 on 2023-10-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bblist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
    ]
