# Generated by Django 4.2.1 on 2023-08-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bblist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=100, verbose_name='Вкус')),
                ('topping', models.CharField(max_length=100, verbose_name='Топпинг')),
                ('price', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Цена')),
            ],
        ),
    ]
