# Generated by Django 4.2.1 on 2023-10-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bblist', '0002_remove_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_login_required',
            field=models.BooleanField(default=False, verbose_name='Требуется вход'),
        ),
    ]
