# Generated by Django 4.2 on 2023-09-21 17:07

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_bbcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BBCode',
        ),
        migrations.AddField(
            model_name='bb',
            name='_content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, no_rendered_field=True, null=True, verbose_name='Описание'),
        ),
    ]
