# Generated by Django 4.2.1 on 2023-06-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_alter_bb_options_alter_bb_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('b', 'Куплю'), ('s', 'Продам'), ('c', 'Поменяю')], default='s', max_length=1, verbose_name='Тип объявления'),
        ),
    ]
