# Generated by Django 4.2.1 on 2023-05-31 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=50, verbose_name='Вкус')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
            ],
        ),
        migrations.CreateModel(
            name='IceCreamKiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('ice_creams', models.ManyToManyField(to='home.icecream', verbose_name='Мороженое')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.person', verbose_name='Родитель')),
            ],
        ),
    ]
