# Generated by Django 4.2.1 on 2023-05-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.person', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='flavor',
            field=models.CharField(max_length=50, verbose_name='Вкус'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='icecreamkiosk',
            name='ice_creams',
            field=models.ManyToManyField(to='home.icecream', verbose_name='Мороженое'),
        ),
        migrations.AlterField(
            model_name='icecreamkiosk',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='icecreamkiosk',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
