# Generated by Django 4.2.1 on 2023-05-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='age',
            field=models.PositiveIntegerField(default=1, verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
