# Generated by Django 4.2.1 on 2023-05-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст'),
        ),
    ]
